### ISSUE TITLE
用户名或密码失效

### ISSUE THREAD

**Issue by tmacdwh1986** [huqi1/City_Fire#4]
您好，请问能把您这边的用户名或者密码再开放一下吗。我想尝试走一遍用例。多谢

**Comment by huqi1** [comment]
> 您好，请问能把您这边的用户名或者密码再开放一下吗。我想尝试走一遍用例。多谢

已经解决，总是有人喜欢测改密码功能，改了又不改回来

**Comment by tmacdwh1986** [comment]
非常感谢
