### ISSUE TITLE
项目克隆下来后访问不到前端页面，能访问到 http://127.0.0.1:8080/city-fire/swagger-ui.html#/

### ISSUE THREAD

**Issue by dragonknightjaja** [huqi1/City_Fire#7]
前端页面没有显示出来，是代理没有设置正确吗
![image](https://user-images.githubusercontent.com/49389980/64484965-4ea08180-d24c-11e9-8b72-96b50398e294.png)
![image](https://user-images.githubusercontent.com/49389980/64484968-6bd55000-d24c-11e9-96ba-0830b0916297.png)

**Comment by dragonknightjaja** [comment]
![image](https://user-images.githubusercontent.com/49389980/64519096-0e153680-d326-11e9-92fb-3ec760952ccb.png)

**Comment by 1x997** [comment]
为森么后来的我压根儿没找见swagger-ui.html这个文件啊，搞不懂
